### ISSUE TITLE
Error running desktop on the template project

### ISSUE THREAD

**Issue by gumil** [littlektframework/littlekt-game-template#4]
I receive this stacktrace when running the desktop app in the sample app.
```
Exception in thread "main" java.lang.IllegalStateException: GLFW may only be used on the main thread and that thread must be the first thread in the process. Please run the JVM with -XstartOnFirstThread. This check may be disabled with Configuration.GLFW_CHECK_THREAD0.
	at org.lwjgl.glfw.EventLoop.check(EventLoop.java:33)
	at org.lwjgl.glfw.GLFW.glfwInit(GLFW.java:1078)
	at com.lehaine.littlekt.LwjglContext$start$1.invokeSuspend(LwjglContext.kt:79)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at com.lehaine.littlekt.LwjglContext.start$core(LwjglContext.kt:73)
	at com.lehaine.littlekt.LittleKtApp.start(LittleKtApp.kt:14)
	at com.game.template.LwjglAppKt.main(LwjglApp.kt:12)
	at com.game.template.LwjglAppKt.main(LwjglApp.kt)
```

Android and JS works.

**Comment by LeHaine** [comment]
Hiya. I assume you are using a Mac? You will need to run it on JVM with the argument that is states in the stacktrace you posted: `-XStartOnFirstThread`

**Comment by gumil** [comment]
@LeHaine hey I'm not sure if I'm doing something wrong but I still get the error
<img width="1586" alt="Screenshot 2023-12-12 at 18 34 04" src="https://github.com/littlektframework/littlekt-game-template/assets/6756250/f3b3c047-a3fe-4900-9fc0-1ad33a1b90d5">
<img width="834" alt="Screenshot 2023-12-12 at 18 34 16" src="https://github.com/littlektframework/littlekt-game-template/assets/6756250/91cbbc75-5d38-4cff-8d30-5977a73cc42f">

**Comment by LeHaine** [comment]
> @LeHaine hey I'm not sure if I'm doing something wrong but I still get the error
> <img width="1586" alt="Screenshot 2023-12-12 at 18 34 04" src="https://github.com/littlektframework/littlekt-game-template/assets/6756250/f3b3c047-a3fe-4900-9fc0-1ad33a1b90d5">
> <img width="834" alt="Screenshot 2023-12-12 at 18 34 16" src="https://github.com/littlektframework/littlekt-game-template/assets/6756250/91cbbc75-5d38-4cff-8d30-5977a73cc42f">
> 

I am not seeing any issues from your screenshot. Is there any other error message or is it still complaining about the thread? Unfortunately, I don't have any Mac hardware to test this out.

**Comment by gumil** [comment]
> I am not seeing any issues from your screenshot. Is there any other error message or is it still complaining about the thread? Unfortunately, I don't have any Mac hardware to test this out.

It's still complaining about the thread. Ah okay, I'll dig into this more. It's weird that it does not fix the threads by adding the `-XstartOnFirstThread`

**Comment by RubenBez** [comment]
I found this issue on youtrack. The workaround posted seems to work for me

https://youtrack.jetbrains.com/issue/KT-62214/XstartOnFirstThread-seems-not-to-be-picked-up-when-using-the-Kotlin-Multiplatform-plugin

**Comment by gumil** [comment]
> I found this issue on youtrack. The workaround posted seems to work for me
> 
> https://youtrack.jetbrains.com/issue/KT-62214/XstartOnFirstThread-seems-not-to-be-picked-up-when-using-the-Kotlin-Multiplatform-plugin

Let me try this one. I settled for executing a command line from gradle:
```kotlin
register("runJar") {
    dependsOn(named("copyResources"), named("packageFatJar") )
    mustRunAfter(named("packageFatJar"))
    doLast {
        exec {
            workingDir = file("${layout.buildDirectory.asFile.get().absolutePath}/publish/")
            executable = "java"
            args = listOf("-XstartOnFirstThread", "-jar", "game-1.0-all.jar")
        }
    }
}
```

**Comment by LeHaine** [comment]
@RubenBez thanks for this!

I updated the master branch with the workaround. I am unable to test for Mac but can either of you confirm it works?

**Comment by RubenBez** [comment]
Yeah, I tested this on a M2 Mac and it seems to work
